17-sprint add stats module
Victor-Ogurtsov/java-explore-with-me pull request #1
Opened 2024-11-20 11:41 UTC by Victor-Ogurtsov

2024-11-21 06:00 UTC, ErkinKasymaliev requested changes
привет, оставил комменты!
один момент еще: если метод используется внутри класса ставьте аннотацию private

2024-11-21 06:00 UTC, ErkinKasymaliev commented on stats/stats-server/src/main/java/ru/practicum/EndpointHitController.java
> +    List<StatsDto> getStats(@RequestParam String start, @RequestParam String end, @RequestParam(required = false) List<String> uris,
@RequestParam String start, @RequestParam String end здесь используйте LocalDate с аннотацией @DateTimeFormatter и в сервисе не надо парсить String в LocalDate

2024-11-21 11:53 UTC, Victor-Ogurtsov commented on stats/stats-server/src/main/java/ru/practicum/EndpointHitController.java
> +    List<StatsDto> getStats(@RequestParam String start, @RequestParam String end, @RequestParam(required = false) List<String> uris,
Спасибо, поправлю. 
Еще хотел посоветоваться, в контроллере  по пути GET /stats, не передается параметр "app" и сейчас по моей логике, если в базу несколько сервисов отправляют статистику и у них вдруг оказались одинаковые эндпоинты, то даже если один сервис запросит свою статистику ему будут из базы доставаться данные по разным сервисам (Ведь сами (uri    string) могут быть одинаковыми у разных "ewm-main-service№1" и "ewm-main-service№2". )

Получается выдача плохая, зачем любому сервису анализ данных другого какого-то сервиса. Наверное правильно было бы передавать в сервис статистики при запросе  GET /stats хотя бы в заголовке параметр "app". 
Но вот думаю пройду ли я тесты если так построю логику.

2024-11-22 06:21 UTC, ErkinKasymaliev approved these changes
привет, работа принята

2024-11-22 08:30 UTC, merged